"""
Bias Report & Model Card Generator
───────────────────────────────────
Auto-generates a structured bias report following the
Model Cards for Model Reporting framework (Mitchell et al., 2019).
"""

from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd
from jinja2 import Template


REPORT_TEMPLATE = """# Bias Audit Report: {{ model_name }}

**Generated:** {{ timestamp }}
**Auditor:** LLM-Bias-Miner v1.0
**Methodology:** Data Mining-Based Systematic Bias Audit

---

## 1. Executive Summary

This report presents a systematic bias audit of **{{ model_name }}** using
four data mining methods: association rule mining, subgroup discovery,
anomaly detection, and statistical hypothesis testing.

- **Total prompts analyzed:** {{ n_prompts }}
- **Total responses analyzed:** {{ n_responses }}
- **Demographic dimensions:** {{ n_demographics }}
- **Scenario categories:** {{ categories | join(', ') }}

### Key Findings

{% if significant_count > 0 %}
- **{{ significant_count }}** statistically significant bias findings detected
- **{{ high_concern_count }}** high-concern fairness gaps identified
- **{{ n_rules }}** bias association rules discovered
- **{{ n_subgroups }}** biased subgroups found
{% else %}
- No statistically significant bias findings at the configured thresholds
{% endif %}

---

## 2. Methodology

### 2.1 Prompt Design

Prompts were generated by systematically varying demographic attributes
across {{ n_templates }} scenario templates covering: {{ categories | join(', ') }}.

**Demographic attributes tested:**
{% for dim, values in demographics.items() %}
- **{{ dim }}**: {{ values | join(', ') }}
{% endfor %}

### 2.2 Analysis Pipeline

1. **Response Feature Extraction** — HF Transformers pipelines:
   - Sentiment: `{{ sentiment_model }}`
   - Toxicity: `{{ toxicity_model }}`
   - Regard: `{{ regard_model }}`
   - Embeddings: `{{ embedding_model }}`

2. **Association Rule Mining** — Apriori algorithm with min_support={{ assoc_config.min_support }},
   min_confidence={{ assoc_config.min_confidence }}, min_lift={{ assoc_config.min_lift }}

3. **Subgroup Discovery** — Beam search (width={{ subgroup_config.beam_width }},
   depth={{ subgroup_config.max_depth }}, quality={{ subgroup_config.quality_measure }})

4. **Anomaly Detection** — PyTorch autoencoder on sentence embeddings

5. **Statistical Testing** — Pairwise Welch's t-tests with
   {{ stats_config.correction_method }} correction (α={{ stats_config.alpha }})

---

## 3. Results

### 3.1 Association Rule Mining

{{ assoc_summary }}

{% if top_rules %}
**Top 5 bias rules by lift:**

| Rule | Support | Confidence | Lift |
|------|---------|------------|------|
{% for r in top_rules %}| {{ r.antecedent }} → {{ r.consequent }} | {{ "%.3f" | format(r.support) }} | {{ "%.3f" | format(r.confidence) }} | {{ "%.2f" | format(r.lift) }} |
{% endfor %}
{% endif %}

### 3.2 Subgroup Discovery

{{ subgroup_summary }}

{% if top_subgroups %}
**Top biased subgroups:**

| Subgroup | Size | Mean | Pop. Mean | Effect Size | p-value |
|----------|------|------|-----------|-------------|---------|
{% for s in top_subgroups %}| {{ s.subgroup }} | {{ s.size }} | {{ "%.3f" | format(s.target_mean) }} | {{ "%.3f" | format(s.population_mean) }} | {{ "%.2f" | format(s.effect_size) }} | {{ "%.4f" | format(s.p_value) }} |
{% endfor %}
{% endif %}

### 3.3 Anomaly Detection

{{ anomaly_summary }}

### 3.4 Statistical Testing

{{ stats_summary }}

{% if fairness_table is not none and fairness_table | length > 0 %}
### 3.5 Fairness Metric Summary

| Demographic | Metric | Max Gap | Concern |
|-------------|--------|---------|---------|
{% for f in fairness_table %}| {{ f.demographic }} | {{ f.metric }} | {{ "%.4f" | format(f.max_gap) }} | {{ f.fairness_concern }} |
{% endfor %}
{% endif %}

---

## 4. Recommendations

Based on the audit findings:

{% if significant_count > 0 %}
1. **Investigate high-lift association rules** — These patterns indicate systematic
   differential treatment correlated with demographics.
2. **Review biased subgroups** — Intersectional groups flagged by subgroup discovery
   may require targeted evaluation and mitigation.
3. **Examine anomalous response patterns** — Groups with high reconstruction error
   receive qualitatively different responses that warrant human review.
4. **Consider targeted fine-tuning** — RLHF or Constitutional AI methods can
   address specific bias patterns identified in this audit.
{% else %}
1. The model shows no significant bias at the configured thresholds.
2. Consider re-running with lower thresholds or additional prompt templates.
3. Absence of detected bias does not guarantee fairness in all contexts.
{% endif %}

---

## 5. Limitations

- This audit covers {{ n_demographics }} demographic dimensions. Other dimensions
  (disability, nationality, language, etc.) were not tested.
- Prompt templates may not capture all real-world interaction patterns.
- Sentiment and toxicity models used for analysis have their own biases.
- Results are specific to the generation parameters used (temp={{ gen_temp }}).

---

## 6. Reproducibility

All code, prompts, and configuration files are available in this repository.
To reproduce: `python experiments/run_full_audit.py --config config/default_config.yaml`

---

*Report generated by [LLM-Bias-Miner](https://github.com/YOUR_USERNAME/llm-bias-miner)*
"""


class BiasReportGenerator:
    """Generate a comprehensive bias audit report."""

    def __init__(self, output_dir: str = "results"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        df: pd.DataFrame,
        config: dict,
        assoc_summary: str = "",
        subgroup_summary: str = "",
        anomaly_summary: str = "",
        stats_summary: str = "",
        rules_df: Optional[pd.DataFrame] = None,
        subgroups_df: Optional[pd.DataFrame] = None,
        stats_df: Optional[pd.DataFrame] = None,
        fairness_df: Optional[pd.DataFrame] = None,
        model_name: str = "Unknown",
    ) -> str:
        """Generate the full bias report as Markdown."""

        # Count significant findings
        significant_count = 0
        if stats_df is not None and "is_significant" in stats_df.columns:
            significant_count = int(stats_df["is_significant"].sum())

        high_concern_count = 0
        if fairness_df is not None and "fairness_concern" in fairness_df.columns:
            high_concern_count = int((fairness_df["fairness_concern"] == "HIGH").sum())

        # Prepare top rules
        top_rules = []
        if rules_df is not None and len(rules_df) > 0:
            for _, row in rules_df.head(5).iterrows():
                top_rules.append(row.to_dict())

        # Prepare top subgroups
        top_subgroups = []
        if subgroups_df is not None and len(subgroups_df) > 0:
            for _, row in subgroups_df.head(5).iterrows():
                top_subgroups.append(row.to_dict())

        # Prepare fairness table
        fairness_table = []
        if fairness_df is not None and len(fairness_df) > 0:
            for _, row in fairness_df.iterrows():
                fairness_table.append(row.to_dict())

        # Render template
        template = Template(REPORT_TEMPLATE)
        report = template.render(
            model_name=model_name,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            n_prompts=df["prompt_id"].nunique() if "prompt_id" in df.columns else len(df),
            n_responses=len(df),
            n_demographics=len(config.get("prompts", {}).get("demographics", [])),
            categories=sorted(df["category"].unique().tolist()) if "category" in df.columns else [],
            n_templates=df["template_name"].nunique() if "template_name" in df.columns else 0,
            demographics=config.get("demographics_used", {}),
            sentiment_model=config.get("analysis", {}).get("sentiment_model", "N/A"),
            toxicity_model=config.get("analysis", {}).get("toxicity_model", "N/A"),
            regard_model=config.get("analysis", {}).get("regard_model", "N/A"),
            embedding_model=config.get("analysis", {}).get("embedding_model", "N/A"),
            assoc_config=type("C", (), config.get("association_mining", {}))(),
            subgroup_config=type("C", (), config.get("subgroup_discovery", {}))(),
            stats_config=type("C", (), config.get("statistical_testing", {}))(),
            gen_temp=config.get("model", {}).get("temperature", "N/A"),
            significant_count=significant_count,
            high_concern_count=high_concern_count,
            n_rules=len(rules_df) if rules_df is not None else 0,
            n_subgroups=len(subgroups_df) if subgroups_df is not None else 0,
            assoc_summary=assoc_summary,
            subgroup_summary=subgroup_summary,
            anomaly_summary=anomaly_summary,
            stats_summary=stats_summary,
            top_rules=top_rules,
            top_subgroups=top_subgroups,
            fairness_table=fairness_table,
        )

        # Save
        report_path = self.output_dir / "bias_report.md"
        report_path.write_text(report)
        print(f"Bias report saved to {report_path}")
        return report
